---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ printf "alertmanager-%s" .Release.Name | trunc 63 }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "labels.alertmanager" . | indent 4 }}
spec:
  replicas: 1
  template:
    metadata:
      name: alertmanager
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/alertmanager-configMap.yml") . | sha256sum }}
      labels:
{{ include "labels.alertmanager" . | indent 8 }}
    spec:
      containers:
      - name: alertmanager
        image: {{ .Values.images.prometheusAlertmanager.repository }}:{{ .Values.images.prometheusAlertmanager.tag }}
        args:
          - '-config.file=/etc/alertmanager/config.yml'
          - '-storage.path=/alertmanager'
        ports:
        - name: alertmanager
          containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        # - name: templates-volume
        #   mountPath: /etc/alertmanager-templates
        - name: alertmanager
          mountPath: /alertmanager
        livenessProbe:
          httpGet:
            path: /
            port: 9093
        readinessProbe:
          httpGet:
            path: /
            port: 9093
      volumes:
      - name: config-volume
        configMap:
          name: {{ printf "prometheus-alertmanager-%s" .Release.Name | trunc 63 }}
      # - name: templates-volume
      #   configMap:
      #     name: alertmanager-templates
      - name: alertmanager
        emptyDir: {}