---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "prometheus-alertmanager-%s" .Release.Name | trunc 63 }}
  namespace: {{ .Values.namespace }}
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
      slack_api_url: '{{ required "https://slack.com/api/" .Values.slackApiUrl }}'

    route:
      group_by: ['kubernetes']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 5m
      receiver: slack_alert

    receivers:
    - name: 'slack_alert'
      slack_configs:
      - channel: '#alert'
        send_resolved: true

