---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.prometheusAlertmanager.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    prometheus.io/probe: "true"
  labels:
{{ include "labels.alertmanager" . | indent 4 }}
spec:
  type: NodePort
  ports:
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093
  selector:
{{ include "labels.alertmanager" . | indent 4 }}