---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "prometheus-alertmanager-%s" .Release.Name | trunc 63 }}
  namespace: {{ .Values.namespace }}
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
      slack_api_url: '{{ required "https://slack.com/api/" .Values.slackApiUrl }}'

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 5m

      routes:
      - match:
          severity: ^([a-bA-Z]*)$
        receiver: webhook_k8s
        continue: true
      - match:
          severity: ^([a-bA-Z]*)$
        receiver: slack_alert
        continue: true

    receivers:
    - name: 'slack_alert'
      slack_configs:
      - channel: {{ .Values.slackChannel }}
        send_resolved: true
    - name: 'webhook_k8s'
      webhook_configs:
      - url: {{ .Values.web_hook }}
        send_resolved: true

