---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "kube-state-metrics-%s" .Release.Name | trunc 63 }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "labels.kubeStateMetrics" . | indent 4 }}
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: kube-state-metrics
    port: 8080
    protocol: TCP
  selector:
{{ include "labels.kubeStateMetrics" . | indent 4 }}
