---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.kubeStateMetrics.name }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "labels.kubeStateMetrics" . | indent 4 }}
  annotations:
    prometheus.io/probe: "true"
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: kube-state-metrics
    port: 8080
    protocol: TCP
  selector:
{{ include "labels.kubeStateMetrics" . | indent 4 }}
