---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.prometheusCore.name }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "labels.core" . | indent 4 }}
  annotations:
    prometheus.io/probe: "true"
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  ports:
  - name: webui
    port: 9090
    nodePort: 31500
  selector:
{{ include "labels.core" . | indent 4 }}
