---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}
  labels:
{{ include "labels.core" . | indent 4 }}
  annotations:
    prometheus.io/probe: "true"
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  ports:
    - port: 9090
      protocol: TCP
      name: webui
  selector:
{{ include "labels.core" . | indent 4 }}
