# Default values for iNu-prometheus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
namespace: kube-system
images:
  pullPolicy: IfNotPresent
  prometheusCore:
    repository: prom/prometheus
    tag: v1.6.2
    recordTime: 2400h
    recordInterval: 10s
    dataPath: /var/lib/prometheus/data
  prometheusNodeExporter:
    repository: prom/node-exporter
    tag: v0.14.0
  kubeStateMetrics:
    repository: gcr.io/google_containers/kube-state-metrics
    tag: v0.5.0
resources:
  requests:
    cpu: 500m
    memory: 512M